# Generated by Django 2.1 on 2019-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_ip', models.CharField(max_length=250, verbose_name='IP адресс оборудования')),
                ('text', models.TextField(verbose_name='Список изменений')),
                ('date_now', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
