# Generated by Django 2.1.5 on 2019-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglists', '0002_auto_20190126_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
