# Generated by Django 2.1.5 on 2019-02-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglists', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='loglists.Tag'),
        ),
    ]
