# Generated by Django 2.1.5 on 2019-02-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loglists', '0005_auto_20190202_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
